### ISSUE TITLE
Non-leap-year day numbering

### ISSUE THREAD

**Issue by sidpalas** [jmaslin/birthday#1]
Cool project (you get a star!)

Because you wrote this in 2016 you may not have noticed this... but in any year that is not a leap year, every date from March 1 - Dec 31 will display as the previous day.

You could use `moment().isLeapYear();` when calculating the day number to fix this.

🥑

**Comment by jmaslin** [comment]
Thanks Sid, and nice catch! We may not have a `CONTRIBUTE.md` yet but pull requests are always awesome 🥇

**Comment by jmaslin** [comment]
Fixed by #2
